version: '3'
services:
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"    
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=sagademo
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=mypassword
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            - ZOOKEEPER_CLIENT_PORT=32181
            - ZOOKEEPER_TICK_TIME=2000     
    kafka:
        image: confluentinc/cp-kafka:latest
        ports:
            - "19092:19092"
        depends_on:
            - zookeeper
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT            
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    kafkadrop:
        image: obsidiandynamics/kafdrop
        ports: 
            - "9000:9000"
        depends_on: 
            - kafka
        environment: 
            - KAFKA_BROKERCONNECT=kafka:9092
            - JVM_OPTS=-Xms32M -Xmx64M
            - SERVER_SERVLET_CONTEXTPATH=/
    order:
        build:
            context: "order"
        depends_on: 
            - kafka
            - mysql
        ports: 
            - "8080:8080"
        environment: 
            - DB_HOST=mysql
            - DB_USERNAME=myuser
            - DB_PASSWORD=mypassword
            - KAFKA_URL=kafka:9092
        command: ./wait-for-it.sh -t 0 mysql:3306 -- npm start
    payment:
        build:
            context: "payment"
        depends_on: 
            - kafka
            - mysql
        ports: 
            - "8081:8081"
        environment: 
            - JAVAX_SQL_DATASOURCE_BALANCEDATASOURCE_DATASOURCE_URL=jdbc:mysql://mysql:3306/sagademo
            - JAVAX_SQL_DATASOURCE_BALANCEDATASOURCE_DATASOURCE_USER=myuser
            - JAVAX_SQL_DATASOURCE_BALANCEDATASOURCE_DATASOURCE_PASSWORD=mypassword
            - KAFKA_URL=kafka:9092
    orchestrator:
        build:
            context: "orchestrator"
        depends_on: 
            - kafka
            - mysql
            - order
            - payment
        environment: 
            - KAFKA_URL=kafka:9092
