server:
    port: 8082
javax:
    sql:
        DataSource:
            balanceDataSource:
                dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
                dataSource:
                    url: jdbc:mysql://localhost:3306/sagademo
                    user: myuser
                    password: mypassword